SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE cesiones;
INSERT INTO cesiones (id_cesion, titular, cesionario, testigos, id_expediente) VALUES
(1, 'Jose Luis Hernandez Garcia', 'Maria Elena Rodriguez Lopez', 'Pedro Martinez, Juan Carlos Gonzalez', 1),
(2, 'Maria Elena Rodriguez Lopez', 'Pedro Antonio Martinez Sanchez', 'Rosa Maria Perez, Miguel Ramirez', 2),
(3, 'Pedro Antonio Martinez Sanchez', 'Juan Carlos Gonzalez Fernandez', 'Ana Laura Flores, Carlos Morales', 3),
(4, 'Juan Carlos Gonzalez Fernandez', 'Rosa Maria Perez Gomez', 'Miguel Ramirez, Ana Flores', 4),
(5, 'Rosa Maria Perez Gomez', 'Miguel Angel Ramirez Torres', 'Carlos Morales, Laura Reyes', 5),
(6, 'Miguel Angel Ramirez Torres', 'Ana Laura Flores Rivera', 'Francisco Javier, Patricia Guadalupe', 6),
(7, 'Ana Laura Flores Rivera', 'Carlos Eduardo Morales Vazquez', 'Roberto Carlos, Sandra Ivette', 7),
(8, 'Carlos Eduardo Morales Vazquez', 'Laura Patricia Reyes Cruz', 'Alejandro, Veronica', 8),
(9, 'Laura Patricia Reyes Cruz', 'Francisco Javier Gutierrez Ortiz', 'David Omar, Elena', 9),
(10, 'Francisco Javier Gutierrez Ortiz', 'Patricia Guadalupe Jimenez Mendoza', 'Jorge Alberto, Gabriela', 10),
(11, 'Patricia Guadalupe Jimenez Mendoza', 'Roberto Carlos Ruiz Alvarez', 'Luis Manuel, Cristina', 11),
(12, 'Roberto Carlos Ruiz Alvarez', 'Sandra Ivette Vega Diaz', 'Raul, Maria Guadalupe', 12),
(13, 'Sandra Ivette Vega Diaz', 'Alejandro Herrera Romero', 'Sergio, Ana Bertha', 13),
(14, 'Alejandro Herrera Romero', 'Veronica Campos Nava', 'Javier, Leticia', 14),
(15, 'Veronica Campos Nava', 'David Omar Navarro Leiva', 'Ignacio, Carmen', 15),
(16, 'David Omar Navarro Leiva', 'Elena Mendez Castro', 'Manuel, Diana', 16),
(17, 'Elena Mendez Castro', 'Jorge Alberto Luna Orozco', 'Victor Hugo, Alma Rosa', 17),
(18, 'Jorge Alberto Luna Orozco', 'Gabriela Sandoval Aguilar', 'Daniel, Ofelia', 18),
(19, 'Gabriela Sandoval Aguilar', 'Luis Manuel Cortez Arias', 'Marco Antonio, Blanca', 19),
(20, 'Luis Manuel Cortez Arias', 'Cristina Moreno Castillo', 'Francisco, Angeles', 20),
(21, 'Cristina Moreno Castillo', 'Raul Medina Valdez', 'Gustavo, Esmeralda', 21),
(22, 'Raul Medina Valdez', 'Maria Guadalupe Escobedo Aguirre', 'Adrian, Marisol', 22),
(23, 'Maria Guadalupe Escobedo Aguirre', 'Sergio Vargas Campos', 'Oscar, Yolanda', 23),
(24, 'Sergio Vargas Campos', 'Ana Bertha Cordoba Zamora', 'Enrique, Maria Trinidad', 24),
(25, 'Ana Bertha Cordoba Zamora', 'Javier Estrada Linares', 'Ricardo, Luz Maria', 25),
(26, 'Javier Estrada Linares', 'Leticia Mejia Santos', 'Fernando, Claudia', 26),
(27, 'Leticia Mejia Santos', 'Ignacio Huerta Trujillo', 'Jose Manuel, Silvia', 27),
(28, 'Ignacio Huerta Trujillo', 'Carmen Salazar Ramos', 'Arturo, Irene', 28),
(29, 'Carmen Salazar Ramos', 'Manuel Lozano Barrera', 'Armando, Teresa', 29),
(30, 'Manuel Lozano Barrera', 'Diana Garcia Marin', 'Saul, Maria Clementina', 30),
(31, 'Diana Garcia Marin', 'Victor Hugo Ramos Cerda', 'Israel, Juana', 31),
(32, 'Victor Hugo Ramos Cerda', 'Alma Rosa Hernandez Espinoza', 'Juan Pablo, Elizabeth', 32),
(33, 'Alma Rosa Hernandez Espinoza', 'Daniel Lopez Mendez', 'Felipe de Jesus, Gloria', 33),
(34, 'Daniel Lopez Mendez', 'Ofelia Chavez Guerrero', 'Hector, Martha', 34),
(35, 'Ofelia Chavez Guerrero', 'Marco Antonio Santos Perez', 'Ruben, Norma', 35),
(36, 'Marco Antonio Santos Perez', 'Blanca Castillo Toledo', 'Alfredo, Alicia', 36),
(37, 'Blanca Castillo Toledo', 'Francisco Ochoa Valencia', 'Ernesto, Maria de Jesus', 37),
(38, 'Francisco Ochoa Valencia', 'Angeles Valencia Montoya', 'Jose de Jesus, Sofia', 38),
(39, 'Angeles Valencia Montoya', 'Gustavo Aguilar Soto', 'Tomas, Lourdes', 39),
(40, 'Gustavo Aguilar Soto', 'Esmeralda Rojas Mora', 'Damian, Karina', 40),
(41, 'Esmeralda Rojas Mora', 'Adrian Molina Velasco', 'Eduardo, Miriam', 41),
(42, 'Adrian Molina Velasco', 'Marisol Ibarra Rentería', 'Julio, Azucena', 42),
(43, 'Marisol Ibarra Rentería', 'Oscar Flores Quintana', 'Salvador, Rosa Isela', 43),
(44, 'Oscar Flores Quintana', 'Yolanda Delgado Uribe', 'Genaro, Maria de la Luz', 44),
(45, 'Yolanda Delgado Uribe', 'Enrique Murillo Zarate', 'Cesar, Patricia', 45),
(46, 'Enrique Murillo Zarate', 'Maria Trinidad Ponce Vigil', 'Martin, Beatriz', 46),
(47, 'Maria Trinidad Ponce Vigil', 'Ricardo Benitez Palacios', 'Ramon, Elvia', 47),
(48, 'Ricardo Benitez Palacios', 'Luz Maria Arias Granados', 'Humberto, Ma. Elena', 48),
(49, 'Luz Maria Arias Granados', 'Fernando Cifuentes Arriaga', 'Luis, Maria Antonieta', 49),
(50, 'Fernando Cifuentes Arriaga', 'Claudia Acosta Lira', 'Jesus, Carolina', 50),
(51, 'Claudia Acosta Lira', 'Jose Manuel Solano Cardenas', 'Juan Manuel, Jose Luis', 51),
(52, 'Jose Manuel Solano Cardenas', 'Silvia Galvez Cornejo', 'Maria Elena, Pedro Antonio', 52),
(53, 'Silvia Galvez Cornejo', 'Arturo Tapia Saldivar', 'Juan Carlos, Rosa Maria', 53),
(54, 'Arturo Tapia Saldivar', 'Irene Pineda Cano', 'Miguel Angel, Ana Laura', 54),
(55, 'Irene Pineda Cano', 'Armando Vera Galicia', 'Carlos Eduardo, Laura Patricia', 55),
(56, 'Armando Vera Galicia', 'Teresa Arellano Otero', 'Francisco Javier, Patricia Guadalupe', 56),
(57, 'Teresa Arellano Otero', 'Saul Villegas Palma', 'Roberto Carlos, Sandra Ivette', 57),
(58, 'Saul Villegas Palma', 'Maria Clementina Plata Becerra', 'Alejandro, Veronica', 58),
(59, 'Maria Clementina Plata Becerra', 'Israel Angeles Gonzaga', 'David Omar, Elena', 59),
(60, 'Israel Angeles Gonzaga', 'Juana Carrillo Levy', 'Jorge Alberto, Gabriela', 60),
(61, 'Juana Carrillo Levy', 'Juan Pablo Maciel Cabrera', 'Luis Manuel, Cristina', 61),
(62, 'Juan Pablo Maciel Cabrera', 'Elizabeth Arreola Escobar', 'Raul, Maria Guadalupe', 62),
(63, 'Elizabeth Arreola Escobar', 'Felipe de Jesus Benavides Anaya', 'Sergio, Ana Bertha', 63),
(64, 'Felipe de Jesus Benavides Anaya', 'Gloria Zamora Guevara', 'Javier, Leticia', 64),
(65, 'Gloria Zamora Guevara', 'Hector Avila Hernandez', 'Ignacio, Carmen', 65),
(66, 'Hector Avila Hernandez', 'Martha Lira Segovia', 'Manuel, Diana', 66),
(67, 'Martha Lira Segovia', 'Ruben Alvarado Pimentel', 'Victor Hugo, Alma Rosa', 67),
(68, 'Ruben Alvarado Pimentel', 'Norma Ayala Bernal', 'Daniel, Ofelia', 68),
(69, 'Norma Ayala Bernal', 'Alfredo Zuniga Gamez', 'Marco Antonio, Blanca', 69),
(70, 'Alfredo Zuniga Gamez', 'Alicia Morales Vera', 'Francisco, Angeles', 70),
(71, 'Alicia Morales Vera', 'Ernesto Barrera Leal', 'Gustavo, Esmeralda', 71),
(72, 'Ernesto Barrera Leal', 'Maria de Jesus Nieto Rosas', 'Adrian, Marisol', 72),
(73, 'Maria de Jesus Nieto Rosas', 'Jose de Jesus Cornejo Ortega', 'Oscar, Yolanda', 73),
(74, 'Jose de Jesus Cornejo Ortega', 'Sofia Miranda Valle', 'Enrique, Maria Trinidad', 74),
(75, 'Sofia Miranda Valle', 'Tomas Hernandez Acevedo', 'Ricardo, Luz Maria', 75),
(76, 'Tomas Hernandez Acevedo', 'Lourdes Lara Becerra', 'Fernando, Claudia', 76),
(77, 'Lourdes Lara Becerra', 'Damian Salas Zepeda', 'Jose Manuel, Silvia', 77),
(78, 'Damian Salas Zepeda', 'Karina Nava Peralta', 'Arturo, Irene', 78),
(79, 'Karina Nava Peralta', 'Eduardo Mejia Gonzalez', 'Armando, Teresa', 79),
(80, 'Eduardo Mejia Gonzalez', 'Miriam Peralta Avila', 'Saul, Maria Clementina', 80),
(81, 'Miriam Peralta Avila', 'Julio Guzman Lopez', 'Israel, Juana', 81),
(82, 'Julio Guzman Lopez', 'Azucena Rodriguez Herrera', 'Juan Pablo, Elizabeth', 82),
(83, 'Azucena Rodriguez Herrera', 'Salvador Mendez Rodriguez', 'Felipe de Jesus, Gloria', 83),
(84, 'Salvador Mendez Rodriguez', 'Rosa Isela Garcia Soto', 'Hector, Martha', 84),
(85, 'Rosa Isela Garcia Soto', 'Genaro Carranza Morales', 'Ruben, Norma', 85),
(86, 'Genaro Carranza Morales', 'Maria de la Luz Cruz Aguilar', 'Alfredo, Alicia', 86),
(87, 'Maria de la Luz Cruz Aguilar', 'Cesar Gonzalez Martinez', 'Ernesto, Maria de Jesus', 87),
(88, 'Cesar Gonzalez Martinez', 'Patricia Hernandez Ramirez', 'Jose de Jesus, Sofia', 88),
(89, 'Patricia Hernandez Ramirez', 'Martin Valencia Perez', 'Tomas, Lourdes', 89),
(90, 'Martin Valencia Perez', 'Beatriz Gonzalez Garcia', 'Damian, Karina', 90),
(91, 'Beatriz Gonzalez Garcia', 'Ramon Torres Flores', 'Eduardo, Miriam', 91),
(92, 'Ramon Torres Flores', 'Elvia Sanchez Mendez', 'Julio, Azucena', 92),
(93, 'Elvia Sanchez Mendez', 'Humberto Vazquez Ruiz', 'Salvador, Rosa Isela', 93),
(94, 'Humberto Vazquez Ruiz', 'Ma. Elena Perez Garcia', 'Genaro, Maria de la Luz', 94),
(95, 'Ma. Elena Perez Garcia', 'Luis Rodriguez Lopez', 'Cesar, Patricia', 95),
(96, 'Luis Rodriguez Lopez', 'Maria Antonieta Martinez Gonzalez', 'Martin, Beatriz', 96),
(97, 'Maria Antonieta Martinez Gonzalez', 'Jesus Sanchez Torres', 'Ramon, Elvia', 97),
(98, 'Jesus Sanchez Torres', 'Carolina Ramirez Perez', 'Humberto, Ma. Elena', 98),
(99, 'Carolina Ramirez Perez', 'Juan Manuel Garcia Rodriguez', 'Luis, Maria Antonieta', 99),
(100, 'Juan Manuel Garcia Rodriguez', 'Jose Luis Hernandez Garcia', 'Jesus, Carolina', 100);
SET FOREIGN_KEY_CHECKS = 1;