SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE ejidatarios;
INSERT INTO ejidatarios (id_ejidatario, nombre, ap_p, ap_m, estatus, id_ejido) VALUES
(1, 'Jose Luis', 'Hernandez', 'Garcia', 'Activo', 1),
(2, 'Maria Elena', 'Rodriguez', 'Lopez', 'Activo', 2),
(3, 'Pedro Antonio', 'Martinez', 'Sanchez', 'Activo', 3),
(4, 'Juan Carlos', 'Gonzalez', 'Fernandez', 'Activo', 4),
(5, 'Rosa Maria', 'Perez', 'Gomez', 'Activo', 5),
(6, 'Miguel Angel', 'Ramirez', 'Torres', 'Activo', 6),
(7, 'Ana Laura', 'Flores', 'Rivera', 'Activo', 7),
(8, 'Carlos Eduardo', 'Morales', 'Vazquez', 'Activo', 8),
(9, 'Laura Patricia', 'Reyes', 'Cruz', 'Inactivo', 9),
(10, 'Francisco Javier', 'Gutierrez', 'Ortiz', 'Activo', 10),
(11, 'Patricia Guadalupe', 'Jimenez', 'Mendoza', 'Activo', 11),
(12, 'Roberto Carlos', 'Ruiz', 'Alvarez', 'Activo', 12),
(13, 'Sandra Ivette', 'Vega', 'Diaz', 'Activo', 13),
(14, 'Alejandro', 'Herrera', 'Romero', 'Activo', 14),
(15, 'Veronica', 'Campos', 'Nava', 'Activo', 15),
(16, 'David Omar', 'Navarro', 'Leiva', 'Activo', 16),
(17, 'Elena', 'Mendez', 'Castro', 'Activo', 17),
(18, 'Jorge Alberto', 'Luna', 'Orozco', 'Activo', 18),
(19, 'Gabriela', 'Sandoval', 'Aguilar', 'Activo', 19),
(20, 'Luis Manuel', 'Cortez', 'Arias', 'Activo', 20),
(21, 'Cristina', 'Moreno', 'Castillo', 'Activo', 21),
(22, 'Raul', 'Medina', 'Valdez', 'Activo', 22),
(23, 'Maria Guadalupe', 'Escobedo', 'Aguirre', 'Activo', 23),
(24, 'Sergio', 'Vargas', 'Campos', 'Activo', 24),
(25, 'Ana Bertha', 'Cordoba', 'Zamora', 'Activo', 25),
(26, 'Javier', 'Estrada', 'Linares', 'Activo', 26),
(27, 'Leticia', 'Mejia', 'Santos', 'Activo', 27),
(28, 'Ignacio', 'Huerta', 'Trujillo', 'Activo', 28),
(29, 'Carmen', 'Salazar', 'Ramos', 'Activo', 29),
(30, 'Manuel', 'Lozano', 'Barrera', 'Activo', 30),
(31, 'Diana', 'Garcia', 'Marin', 'Activo', 31),
(32, 'Victor Hugo', 'Ramos', 'Cerda', 'Activo', 32),
(33, 'Alma Rosa', 'Hernandez', 'Espinoza', 'Activo', 33),
(34, 'Daniel', 'Lopez', 'Mendez', 'Activo', 34),
(35, 'Ofelia', 'Chavez', 'Guerrero', 'Activo', 35),
(36, 'Marco Antonio', 'Santos', 'Perez', 'Activo', 36),
(37, 'Blanca', 'Castillo', 'Toledo', 'Activo', 37),
(38, 'Francisco', 'Ochoa', 'Valencia', 'Activo', 38),
(39, 'Angeles', 'Valencia', 'Montoya', 'Activo', 39),
(40, 'Gustavo', 'Aguilar', 'Soto', 'Activo', 40),
(41, 'Esmeralda', 'Rojas', 'Mora', 'Activo', 41),
(42, 'Adrian', 'Molina', 'Velasco', 'Activo', 42),
(43, 'Marisol', 'Ibarra', 'Rentería', 'Activo', 43),
(44, 'Oscar', 'Flores', 'Quintana', 'Activo', 44),
(45, 'Yolanda', 'Delgado', 'Uribe', 'Activo', 45),
(46, 'Enrique', 'Murillo', 'Zarate', 'Activo', 46),
(47, 'Maria Trinidad', 'Ponce', 'Vigil', 'Activo', 47),
(48, 'Ricardo', 'Benitez', 'Palacios', 'Activo', 48),
(49, 'Luz Maria', 'Arias', 'Granados', 'Activo', 49),
(50, 'Fernando', 'Cifuentes', 'Arriaga', 'Activo', 50),
(51, 'Claudia', 'Acosta', 'Lira', 'Activo', 51),
(52, 'Jose Manuel', 'Solano', 'Cardenas', 'Activo', 52),
(53, 'Silvia', 'Galvez', 'Cornejo', 'Activo', 53),
(54, 'Arturo', 'Tapia', 'Saldivar', 'Activo', 54),
(55, 'Irene', 'Pineda', 'Cano', 'Activo', 55),
(56, 'Armando', 'Vera', 'Galicia', 'Activo', 56),
(57, 'Teresa', 'Arellano', 'Otero', 'Activo', 57),
(58, 'Saul', 'Villegas', 'Palma', 'Activo', 58),
(59, 'Maria Clementina', 'Plata', 'Becerra', 'Activo', 59),
(60, 'Israel', 'Angeles', 'Gonzaga', 'Activo', 60),
(61, 'Juana', 'Carrillo', 'Levy', 'Activo', 61),
(62, 'Juan Pablo', 'Maciel', 'Cabrera', 'Activo', 62),
(63, 'Elizabeth', 'Arreola', 'Escobar', 'Activo', 63),
(64, 'Felipe de Jesus', 'Benavides', 'Anaya', 'Activo', 64),
(65, 'Gloria', 'Zamora', 'Guevara', 'Activo', 65),
(66, 'Hector', 'Avila', 'Hernandez', 'Activo', 66),
(67, 'Martha', 'Lira', 'Segovia', 'Activo', 67),
(68, 'Ruben', 'Alvarado', 'Pimentel', 'Activo', 68),
(69, 'Norma', 'Ayala', 'Bernal', 'Activo', 69),
(70, 'Alfredo', 'Zuniga', 'Gamez', 'Activo', 70),
(71, 'Alicia', 'Morales', 'Vera', 'Activo', 71),
(72, 'Ernesto', 'Barrera', 'Leal', 'Activo', 72),
(73, 'Maria de Jesus', 'Nieto', 'Rosas', 'Activo', 73),
(74, 'Jose de Jesus', 'Cornejo', 'Ortega', 'Activo', 74),
(75, 'Sofia', 'Miranda', 'Valle', 'Activo', 75),
(76, 'Tomas', 'Hernandez', 'Acevedo', 'Activo', 76),
(77, 'Lourdes', 'Lara', 'Becerra', 'Activo', 77),
(78, 'Damian', 'Salas', 'Zepeda', 'Activo', 78),
(79, 'Karina', 'Nava', 'Peralta', 'Activo', 79),
(80, 'Eduardo', 'Mejia', 'Gonzalez', 'Activo', 80),
(81, 'Miriam', 'Peralta', 'Avila', 'Activo', 81),
(82, 'Julio', 'Guzman', 'Lopez', 'Activo', 82),
(83, 'Azucena', 'Rodriguez', 'Herrera', 'Activo', 83),
(84, 'Salvador', 'Mendez', 'Rodriguez', 'Activo', 84),
(85, 'Rosa Isela', 'Garcia', 'Soto', 'Activo', 85),
(86, 'Genaro', 'Carranza', 'Morales', 'Activo', 86),
(87, 'Maria de la Luz', 'Cruz', 'Aguilar', 'Activo', 87),
(88, 'Cesar', 'Gonzalez', 'Martinez', 'Activo', 88),
(89, 'Patricia', 'Hernandez', 'Ramirez', 'Activo', 89),
(90, 'Martin', 'Valencia', 'Perez', 'Activo', 90),
(91, 'Beatriz', 'Gonzalez', 'Garcia', 'Activo', 91),
(92, 'Ramon', 'Torres', 'Flores', 'Activo', 92),
(93, 'Elvia', 'Sanchez', 'Mendez', 'Activo', 93),
(94, 'Humberto', 'Vazquez', 'Ruiz', 'Activo', 94),
(95, 'Ma. Elena', 'Perez', 'Garcia', 'Activo', 95),
(96, 'Luis', 'Rodriguez', 'Lopez', 'Activo', 96),
(97, 'Maria Antonieta', 'Martinez', 'Gonzalez', 'Activo', 97),
(98, 'Jesus', 'Sanchez', 'Torres', 'Activo', 98),
(99, 'Carolina', 'Ramirez', 'Perez', 'Activo', 99),
(100, 'Juan Manuel', 'Garcia', 'Rodriguez', 'Activo', 100);
SET FOREIGN_KEY_CHECKS = 1;