SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE empleados;
INSERT INTO empleados (id_empleado, nombre, ap_p, ap_m, area, funcion, id_usuario) VALUES
(1, 'Roberto', 'Garcia', 'Lopez', 'Administracion', 'Director General', 1),
(2, 'Patricia', 'Hernandez', 'Martinez', 'Comisaria', 'Comisario Ejidal', 2),
(3, 'Luis Alberto', 'Sanchez', 'Rodriguez', 'Area Legal', 'Abogado', 3),
(4, 'Ana Maria', 'Torres', 'Ramirez', 'Contabilidad', 'Contadora', 4),
(5, 'Miguel', 'Flores', 'Gonzalez', 'Secretaria', 'Secretario', 5),
(6, 'Claudia', 'Vazquez', 'Perez', 'Atencion', 'Atencion al Cliente', 6),
(7, 'Carlos', 'Mendez', 'Jimenez', 'Campo', 'Encargado de Campo', 7),
(8, 'Laura', 'Ruiz', 'Hernandez', 'Archivos', 'Archivo', 8),
(9, 'Jorge', 'Alvarez', 'Castro', 'Tesoreria', 'Tesorero', 9),
(10, 'Sandra', 'Nunez', 'Morales', 'Recepcion', 'Recepcionista', 10),
(11, 'Fernando', 'Gutierrez', 'Ortiz', 'Administracion', 'Administrador', 11),
(12, 'Diana', 'Vega', 'Diaz', 'Comisaria', 'Subcomisario', 12),
(13, 'Alejandro', 'Reyes', 'Flores', 'Area Legal', 'Asesor Legal', 13),
(14, 'Maria del Carmen', 'Luna', 'Vera', 'Contabilidad', 'Auxiliar Contable', 14),
(15, 'Raul', 'Campos', 'Morales', 'Secretaria', 'Secretario de Actas', 15),
(16, 'Guadalupe', 'Navarro', 'Sandoval', 'Atencion', 'Ventanilla', 16),
(17, 'Jose Manuel', 'Cortez', 'Aguilar', 'Campo', 'Topografo', 17),
(18, 'Veronica', 'Medina', 'Estrada', 'Archivos', 'Encargado de Expedientes', 18),
(19, 'Juan Carlos', 'Lozano', 'Herrera', 'Tesorería', 'Cajero', 19),
(20, 'Carmen', 'Arias', 'Ramos', 'Recepcion', 'Recepcion', 20),
(21, 'Sergio', 'Chavez', 'Garcia', 'Administracion', 'Auxiliar Administrativo', 21),
(22, 'Martha', 'Romero', 'Torres', 'Comisaria', 'Coordinadora de Comisaría', 22),
(23, 'Francisco', 'Guzman', 'Espinoza', 'Area Legal', 'Notario', 23),
(24, 'Leticia', 'Aguilar', 'Mendez', 'Contabilidad', 'Contador General', 24),
(25, 'Arturo', 'Pineda', 'Nava', 'Secretaria', 'Escriturario', 25),
(26, 'Irma', 'Rojas', 'Molina', 'Atencion', 'Atencion al Publico', 26),
(27, 'David', 'Cruz', 'Lopez', 'Campo', 'Agrimensor', 27),
(28, 'Rosa Maria', 'Soto', 'Reyes', 'Archivos', 'Digitador', 28),
(29, 'Hector', 'Vigil', 'Mendoza', 'Tesorería', 'Auxiliar de Tesoreria', 29),
(30, 'Silvia', 'Valencia', 'Jimenez', 'Recepcion', 'Mensajeria', 30),
(31, 'Oscar', 'Barrera', 'Gonzalez', 'Administracion', 'Jefe de Rh', 31),
(32, 'Olga', 'Leon', 'Sanchez', 'Comisaria', 'Vocal Propietario', 32),
(33, 'Armando', 'Cabrera', 'Torres', 'Area Legal', 'Gestor', 33),
(34, 'Teresa', 'Salas', 'Morales', 'Contabilidad', 'Auxiliar de Contabilidad', 34),
(35, 'Javier', 'Zamora', 'Hernandez', 'Secretaria', 'Actas y Escrituras', 35),
(36, 'Maria Elena', 'Palacios', 'Garcia', 'Atencion', 'Tramites', 36),
(37, 'Enrique', 'Carrillo', 'Rodriguez', 'Campo', 'Supervisor de Campo', 37),
(38, 'Lucia', 'Benitez', 'Flores', 'Archivos', 'Resguardo de Documentos', 38),
(39, 'Ramon', 'Perez', 'Martinez', 'Tesorería', 'Cobranza', 39),
(40, 'Ana Lilia', 'Hernandez', 'Vazquez', 'Recepcion', 'Archivo de Pagos', 40),
(41, 'Daniel', 'Mendez', 'Cruz', 'Administracion', 'Sistemas', 41),
(42, 'Gloria', 'Garcia', 'Luna', 'Comisaria', 'Vocal Suplente', 42),
(43, 'Saul', 'Rodriguez', 'Ramirez', 'Area Legal', 'Representante Legal', 43),
(44, 'Maria de la Luz', 'Reyes', 'Torres', 'Contabilidad', 'Pagos y Cobros', 44),
(45, 'Manuel', 'Vargas', 'Jimenez', 'Secretaria', 'Escrituras', 45),
(46, 'Patricia', 'Silva', 'Santos', 'Atencion', 'Consultas', 46),
(47, 'Alberto', 'Gonzalez', 'Morales', 'Campo', 'Levantamiento', 47),
(48, 'Elvia', 'Castillo', 'Navarro', 'Archivos', 'Clasificacion', 48),
(49, 'Ricardo', 'Delgado', 'Cortez', 'Tesorería', 'Conciliacion', 49),
(50, 'Sofia', 'Aguirre', 'Campos', 'Recepcion', 'Informes', 50),
(51, 'Jose de Jesus', 'Moreno', 'Garcia', 'Administracion', 'Logistica', 51),
(52, 'Maria Trinidad', 'Estrada', 'Herrera', 'Comisaria', 'Fiscal', 52),
(53, 'Gustavo', 'Cervantes', 'Martinez', 'Area Legal', 'Asesoria', 53),
(54, 'Ana Patricia', 'Rivera', 'Lopez', 'Contabilidad', 'Facturacion', 54),
(55, 'Juan Pablo', 'Espinoza', 'Rodriguez', 'Secretaria', 'Legal', 55),
(56, 'Laura Elena', 'Garcia', 'Gutierrez', 'Atencion', 'Orientacion', 56),
(57, 'Luis Fernando', 'Hernandez', 'Mendez', 'Campo', 'Medicions', 57),
(58, 'Maria Isabel', 'Gomez', 'Perez', 'Archivos', 'Inventario', 58),
(59, 'Victor Manuel', 'Sanchez', 'Torres', 'Tesorería', 'Caja', 59),
(60, 'Claudia Ivette', 'Ramirez', 'Sanchez', 'Recepcion', 'Citas', 60),
(61, 'Eduardo', 'Lopez', 'Garcia', 'Administracion', 'Recursos Materiales', 61),
(62, 'Rosario', 'Flores', 'Gonzalez', 'Comisaria', 'Consejero', 62),
(63, 'Felipe', 'Martinez', 'Rodriguez', 'Area Legal', 'Revision de Documentos', 63),
(64, 'Yolanda', 'Perez', 'Hernandez', 'Contabilidad', 'Nomina', 64),
(65, 'Antonio', 'Soto', 'Ramirez', 'Secretaria', 'Citatorios', 65),
(66, 'Maria del Rosario', 'Cruz', 'Vazquez', 'Atencion', 'Gestion de Turnos', 66),
(67, 'Alfredo', 'Jimenez', 'Morales', 'Campo', 'Verificacion de Parcelas', 67),
(68, 'Beatriz', 'Ortega', 'Garcia', 'Archivos', 'Prestamo de Documentos', 68),
(69, 'Mario', 'Hernandez', 'Torres', 'Tesorería', 'Registro de Pagos', 69),
(70, 'Ana Guadalupe', 'Mendoza', 'Lopez', 'Recepcion', 'Registro', 70),
(71, 'Gerardo', 'Vazquez', 'Ruiz', 'Administracion', 'Mantenimiento', 71),
(72, 'Lidia', 'Garcia', 'Rodriguez', 'Comisaria', 'Vocal', 72),
(73, 'Jorge Luis', 'Ramirez', 'Flores', 'Area Legal', 'Legal', 73),
(74, 'Maria de Jesus', 'Morales', 'Sanchez', 'Contabilidad', 'Estado de Cuenta', 74),
(75, 'Mauricio', 'Torres', 'Hernandez', 'Secretaria', 'Certificados', 75),
(76, 'Sandra Luz', 'Cortez', 'Garcia', 'Atencion', 'Asistencia', 76),
(77, 'Juan Manuel', 'Vega', 'Martinez', 'Campo', 'Registro Parcelario', 77),
(78, 'Maria de la Paz', 'Luna', 'Jimenez', 'Archivos', 'Base de Datos', 78),
(79, 'Francisco Javier', 'Aguilar', 'Perez', 'Tesorería', 'Ingresos', 79),
(80, 'Karina', 'Herrera', 'Torres', 'Recepcion', 'Control', 80),
(81, 'Ignacio', 'Navarro', 'Garcia', 'Administracion', 'Seguridad', 81),
(82, 'Maria de los Angeles', 'Medina', 'Rodriguez', 'Comisaria', 'Comite', 82),
(83, 'Ivan', 'Sandoval', 'Martinez', 'Area Legal', 'Titulos', 83),
(84, 'Veronica', 'Castillo', 'Sanchez', 'Contabilidad', 'Sueldos', 84),
(85, 'Israel', 'Perez', 'Hernandez', 'Secretaria', 'Convocatorias', 85),
(86, 'Maria del Consuelo', 'Lopez', 'Gutierrez', 'Atencion', 'Tramites Agrarios', 86),
(87, 'Luis Miguel', 'Gonzalez', 'Ramirez', 'Campo', 'Georeferenciacion', 87),
(88, 'Ana Karen', 'Reyes', 'Cruz', 'Archivos', 'Digitalizacion', 88),
(89, 'Marco Antonio', 'Vazquez', 'Torres', 'Tesorería', 'Egresos', 89),
(90, 'Gabriela', 'Mendez', 'Jimenez', 'Recepcion', 'Atencion', 90),
(91, 'Pedro', 'Gutierrez', 'Martinez', 'Administracion', 'Planeacion', 91),
(92, 'Maria Guadalupe', 'Sanchez', 'Lopez', 'Comisaria', 'Comite de Vigilancia', 92),
(93, 'Carlos', 'Rodriguez', 'Garcia', 'Area Legal', 'Escrituras', 93),
(94, 'Maria del Pilar', 'Alvarez', 'Hernandez', 'Contabilidad', 'Balances', 94),
(95, 'Jesus', 'Morales', 'Torres', 'Secretaria', 'Actas de Asamblea', 95),
(96, 'Liliana', 'Flores', 'Rodriguez', 'Atencion', 'Gestion', 96),
(97, 'Roberto Carlos', 'Escobedo', 'Mendez', 'Campo', 'Inspeccion', 97),
(98, 'Maria del Carmen', 'Campos', 'Ramirez', 'Archivos', 'Consulta', 98),
(99, 'Alejandro', 'Valencia', 'Sanchez', 'Tesorería', 'Finanzas', 99),
(100, 'Cynthia', 'Gonzalez', 'Perez', 'Recepcion', 'Servicios', 100);
SET FOREIGN_KEY_CHECKS = 1;