SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE expedientes;
INSERT INTO expedientes (id_expediente, demandas, actas) VALUES
(1, 'Solicitud de certificado de parcela', 'Acta de asamblea ordinaria 2025, Acta de verificacion de parcela'),
(2, 'Solicitud de constancia de posesion', 'Acta de posesion, Acta de vecinos'),
(3, 'Solicitud de cesion de derechos', 'Acta de cesion, Testimonios'),
(4, 'Solicitud de actualizacion de datos', 'Acta de actualizacion, Documentacion de identificacion'),
(5, 'Solicitud de certificado parcelario', 'Acta de Inspeccion, Dictamen tecnico'),
(6, 'Solicitud de constancia ejidal', 'Acta de verificacion ejidal, Resolución de comisaría'),
(7, 'Solicitud de deslinde de parcela', 'Acta de deslinde, Mapa oficial'),
(8, 'Solicitud de certificacion', 'Acta de validacion, Documentacion completa'),
(9, 'Cesion de derechos agrarios', 'Acta de cesion entre particulares, Acta de asamblea'),
(10, 'Regularizacion de posesion', 'Acta de posesion historical, Dictamen legal'),
(11, 'Cambio de titular de parcela', 'Acta de transferencia, Resolucion de consejo'),
(12, 'Constancia de propiedad ejidal', 'Acta de verificacion, Certificado de conformidad'),
(13, 'Deslinde administrativo', 'Acta de medicion, Plano topografico'),
(14, 'Actualizacion de datos ejidales', 'Acta deactualizacion, Documentacion personal'),
(15, 'Cesion de derechos autorizada', 'Acta de cesion aprobada, Acta de testigos'),
(16, 'Certificado de parcela', 'Acta de inspeccion parcelaria, Fotografias'),
(17, 'Constancia de posesion', 'Acta de posesion actual, Testimonios de vecinos'),
(18, 'Deslinde tecnico', 'Acta de medicion con GPS, Plano georeferenciado'),
(19, 'Constancia de vigencia', 'Acta de vigencia de derechos, Resolucion'),
(20, 'Cambio de nombre', 'Acta de cambio de nombre, Documentacion legal'),
(21, 'Certificado ejidal', 'Acta de verificacion ejidal, Dictamen de conformidad'),
(22, 'Cesion de derechos', 'Acta de cesion parcelaria, Acta de asamblea'),
(23, 'Actualizacion parcelaria', 'Acta de actualizacion de datos, Plano actualizado'),
(24, 'Constancia de posesion', 'Acta de posesion y disfruta, Testimonios'),
(25, 'Deslinde de parcela', 'Acta de linderos, Medicion oficial'),
(26, 'Cesion de derechos agrarios', 'Acta de cesion entre ejidatarios, Resolucion'),
(27, 'Regularizacion ejidal', 'Acta de regularizacion, Documentacion completa'),
(28, 'Certificado de parcela', 'Acta de inspeccion, Fotos satelitales'),
(29, 'Constancia de propiedad', 'Acta de propiedad, Verificacion de campos'),
(30, 'Cambio de titular', 'Acta de transferencia, Aprobacion de comisaría'),
(31, 'Deslinde administrativo', 'Acta de demarcacion, Plano oficial'),
(32, 'Constancia de ejidatario', 'Acta de registro ejidal, Identificacion oficial'),
(33, 'Cesion de derechos', 'Acta de cesion, Testigos de honor'),
(34, 'Actualizacion de datos', 'Acta de actualizacion, Documentos actualizado'),
(35, 'Constancia de posesion', 'Acta de posesion, Verificacion de terceros'),
(36, 'Regularizacion parcelaria', 'Acta de regularizacion, Dictamen técnico'),
(37, 'Cesion autorizada', 'Acta de cesion aprobada, Resolucion de comisaría'),
(38, 'Certificado parcelario', 'Acta de inspeccion parcelaria, Mapa oficial'),
(39, 'Constancia de vigencia', 'Acta de vigencia, Revisión de status'),
(40, 'Cambio de nombre', 'Acta de cambio, Documentacion legal'),
(41, 'Deslinde de parcela', 'Acta de medicion, Plano catastral'),
(42, 'Cesion de derechos agrarios', 'Acta de cesion, Acta de asamblea'),
(43, 'Actualizacion cadastral', 'Acta de actualizacion, Plano georeferenciado'),
(44, 'Constancia de posesion', 'Acta de posesion actual, Testimonios'),
(45, 'Certificado ejidal', 'Acta de verificacion ejidal, Dictamen'),
(46, 'Cesion de derechos', 'Acta de transferencia, Resolucion'),
(47, 'Regularizacion de derechos', 'Acta de regularizacion, Documentacion'),
(48, 'Constancia de propiedad', 'Acta de propiedad ejidal, Verificacion'),
(49, 'Cambio de titular', 'Acta de cambio de titularidad, Aprobacion'),
(50, 'Deslinde tecnico', 'Acta de medicion GPS, Plano topografico'),
(51, 'Cesion parcelaria', 'Acta de cesion entre ejidatarios, Testigos'),
(52, 'Actualizacion de registros', 'Acta de actualizacion, Documentos vigentes'),
(53, 'Constancia de posesion', 'Acta de posesion, Acta de vecinos'),
(54, 'Nueva asignacion de parcela', 'Acta de asignacion, Resolucion de asamblea'),
(55, 'Cesion de derechos', 'Acta de cesion, Testimonios legales'),
(56, 'Regularizacion agraria', 'Acta de regularizacion, Dictamen técnico'),
(57, 'Actualizacion de datos', 'Acta de actualizacion, Documentacion'),
(58, 'Cambio de nombre', 'Acta de cambio, Identificacion oficial'),
(59, 'Cesion autorizada', 'Acta de cesion aprobada, Resolucion'),
(60, 'Deslinde administrativo', 'Acta de demarcacion, Mapa oficial'),
(61, 'Reconocimiento de posesion', 'Acta de reconocimiento, Testimonios'),
(62, 'Cesion de derechos agrarios', 'Acta de cesion, Aprobacion de consejo'),
(63, 'Modificacion de parcela', 'Acta de modificacion, Plano actualizado'),
(64, 'Constancia de posesion', 'Acta de posesion actual, Verificacion'),
(65, 'Transferencia ejidal', 'Acta de transferencia, Acta de asamblea'),
(66, 'Actualizacion cadastral', 'Acta de actualizacion, Plano georeferenciado'),
(67, 'Cesion de derechos', 'Acta de cesion, Documentacion completa'),
(68, 'Regularizacion parcelaria', 'Acta de regularizacion, Dictamen'),
(69, 'Cambio de nombre', 'Acta de cambio, Documentos legales'),
(70, 'Constancia ejidal', 'Acta de verificacion, Resolucion'),
(71, 'Nueva asignacion', 'Acta de asignacion, Resolucion'),
(72, 'Cesion de derechos agrarios', 'Acta de cesion, Acta de testigos'),
(73, 'Actualizacion parcelaria', 'Acta de actualizacion, Plano atualizado'),
(74, 'Constancia de posesion', 'Acta de posesion, Verificacion de terceros'),
(75, 'Modificacion de derechos', 'Acta de modificacion, Resolucion'),
(76, 'Cesion parcelaria', 'Acta de cesion, Aprobacion'),
(77, 'Regularizacion ejidal', 'Acta de regularizacion, Dictamen legal'),
(78, 'Actualizacion de registros', 'Acta de actualizacion, Documentacion'),
(79, 'Cambio de titular', 'Acta de cambio, Resolucion de comisaría'),
(80, 'Cesion de derechos', 'Acta de cesion, Testimonios'),
(81, 'Reconocimiento ejidal', 'Acta de reconocimiento, Verificacion'),
(82, 'Cesion de derechos', 'Acta de cesion, Documentacion'),
(83, 'Modificacion de parcela', 'Acta de modificacion, Plano'),
(84, 'Transferencia de posesion', 'Acta de transferencia, Acta de vecinos'),
(85, 'Regularizacion ejidal', 'Acta de regularizacion, Dictamen'),
(86, 'Actualizacion cadastral', 'Acta de actualizacion, Plano satelital'),
(87, 'Cambio de nombre', 'Acta de cambio, Documentos'),
(88, 'Cesion autorizada', 'Acta de cesion aprobada, Resolucion'),
(89, 'Reconocimiento de derechos', 'Acta de reconocimiento, Verificacion'),
(90, 'Actualizacion de datos', 'Acta de actualizacion, Documentacion'),
(91, 'Nueva asignacion parcelaria', 'Acta de asignacion, Resolucion de asamblea'),
(92, 'Transferencia de derechos', 'Acta de transferencia, Acta de consejo'),
(93, 'Modificacion de datos', 'Acta de modificacion, Documentacion'),
(94, 'Cesion de derechos agrarios', 'Acta de cesion, Testigos'),
(95, 'Regularizacion parcelaria', 'Acta de regularizacion, Dictamen'),
(96, 'Cambio de titular', 'Acta de cambio, Resolucion'),
(97, 'Actualizacion de registros', 'Acta de actualizacion, Documentos'),
(98, 'Reconocimiento ejidal', 'Acta de reconocimiento, Verificacion'),
(99, 'Cesion de derechos', 'Acta de cesion, Acta de asamblea'),
(100, 'Transferencia parcelaria', 'Acta de transferencia, Resolucion');
SET FOREIGN_KEY_CHECKS = 1;