SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE parcelas;
INSERT INTO parcelas (id_parcela, tamano, colindancias, id_municipio, id_ejidatario) VALUES
(1, '5.50 Has', 'Norte: Ejido La Paz, Sur: Rio Lerma, Este: Terreno Manuel Garcia, Oeste: Camino Real', 1, 1),
(2, '3.25 Has', 'Norte: Terreno Jose Hernandez, Sur: Arroyo Seco, Este: Limite Ejidal, Oeste: Camino Vecinal', 2, 2),
(3, '7.80 Has', 'Norte: Bosque Comunitario, Sur: Rio Azul, Este: Terreno Maria Lopez, Oeste: Carretera Federal', 3, 3),
(4, '4.50 Has', 'Norte: Parcela Pedro Martinez, Sur: Terreno Comun, Este: Rio Salado, Oeste: Camino rural', 4, 4),
(5, '6.25 Has', 'Norte: Ejido San Jose, Sur: Terreno Gonzalez, Este: Loma Alta, Oeste: Canal de Riego', 5, 5),
(6, '2.75 Has', 'Norte: Solar Ejidal, Sur: Terreno Perez, Este: Montaña, Oeste: Sendero', 6, 6),
(7, '8.00 Has', 'Norte: Rio Principal, Sur: Terreno Sanchez, Este: Colindancia Vecina, Oeste: Linea Electrica', 7, 7),
(8, '4.20 Has', 'Norte: Camino Real, Sur: Terreno Rivera, Este: Arroyo, Oeste: Terreno Morales', 8, 8),
(9, '5.75 Has', 'Norte: Terreno Vazquez, Sur: Rio Chico, Este: Lindero, Oeste: Carretera', 9, 9),
(10, '3.50 Has', 'Norte: Ejido Santa Lucia, Sur: Terreno Cruz, Este: Monte, Oeste: Camino', 10, 10),
(11, '6.80 Has', 'Norte: Terreno Gutierrez, Sur: Rio Grande, Este: Terreno Jimenez, Oeste: Brecha', 11, 11),
(12, '4.00 Has', 'Norte: Parcela Ruiz, Sur: Terreno Alvarez, Este: Serrania, Oeste: Rio', 12, 12),
(13, '7.50 Has', 'Norte: Terreno Vega, Sur: Arroyo Nuevo, Este: Lindero Este, Oeste: Camino Rural', 13, 13),
(14, '5.25 Has', 'Norte: Terreno Herrera, Sur: Terreno Campos, Este: Rio Verde, Oeste: Carretera', 14, 14),
(15, '3.80 Has', 'Norte: Terreno Navarro, Sur: Terreno Mendez, Este: Monte Alto, Oeste: Sendero', 15, 15),
(16, '6.50 Has', 'Norte: Ejido Central, Sur: Terreno Luna, Este: Rio Blanco, Oeste: Linea Telefonica', 16, 16),
(17, '4.75 Has', 'Norte: Terreno Sandoval, Sur: Arroyo, Este: Terreno Cortez, Oeste: Camino', 17, 17),
(18, '8.25 Has', 'Norte: Terreno Moreno, Sur: Rio Negro, Este: Montanas, Oeste: Carretera Principal', 18, 18),
(19, '5.00 Has', 'Norte: Terreno Medina, Sur: Terreno Escobedo, Este: Rio Azul, Oeste: Brecha', 19, 19),
(20, '3.25 Has', 'Norte: Terreno Vargas, Sur: Terreno Cordoba, Este: Lindero, Oeste: Camino', 20, 20),
(21, '7.00 Has', 'Norte: Terreno Estrada, Sur: Rio Salado, Este: Terreno Mejia, Oeste: Carretera', 21, 21),
(22, '4.50 Has', 'Norte: Terreno Huerta, Sur: Terreno Salazar, Este: Monte, Oeste: Arroyo', 22, 22),
(23, '6.25 Has', 'Norte: Terreno Lozano, Sur: Terreno Garcia, Este: Rio, Oeste: Camino Rural', 23, 23),
(24, '5.50 Has', 'Norte: Terreno Ramos, Sur: Terreno Hernandez, Este: Serrania, Oeste: Linea', 24, 24),
(25, '3.75 Has', 'Norte: Terreno Lopez, Sur: Terreno Chavez, Este: Arroyo, Oeste: Sendero', 25, 25),
(26, '8.50 Has', 'Norte: Terreno Santos, Sur: Rio Principal, Este: Terreno Castillo, Oeste: Carretera', 26, 26),
(27, '4.25 Has', 'Norte: Terreno Ochoa, Sur: Terreno Valencia, Este: Monte Alto, Oeste: Camino', 27, 27),
(28, '6.00 Has', 'Norte: Terreno Aguilar, Sur: Terreno Rojas, Este: Rio Chico, Oeste: Brecha', 28, 28),
(29, '5.80 Has', 'Norte: Terreno Molina, Sur: Terreno Ibarra, Este: Lindero, Oeste: Carretera', 29, 29),
(30, '3.50 Has', 'Norte: Terreno Flores, Sur: Terreno Delgado, Este: Arroyo, Oeste: Sendero', 30, 30),
(31, '7.25 Has', 'Norte: Terreno Murillo, Sur: Terreno Ponce, Este: Rio, Oeste: Camino Rural', 31, 31),
(32, '4.75 Has', 'Norte: Terreno Benitez, Sur: Terreno Arias, Este: Montaña, Oeste: Linea', 32, 32),
(33, '6.50 Has', 'Norte: Terreno Cifuentes, Sur: Terreno Acosta, Este: Terreno Solano, Oeste: Carretera', 33, 33),
(34, '5.25 Has', 'Norte: Terreno Galvez, Sur: Terreno Tapia, Este: Rio Verde, Oeste: Camino', 34, 34),
(35, '3.80 Has', 'Norte: Terreno Pineda, Sur: Terreno Vera, Este: Lindero, Oeste: Sendero', 35, 35),
(36, '8.00 Has', 'Norte: Terreno Arellano, Sur: Terreno Villegas, Este: Terreno Plata, Oeste: Carretera', 36, 36),
(37, '4.50 Has', 'Norte: Terreno Angeles, Sur: Terreno Carrillo, Este: Monte, Oeste: Arroyo', 37, 37),
(38, '6.75 Has', 'Norte: Terreno Maciel, Sur: Terreno Arreola, Este: Rio, Oeste: Camino Rural', 38, 38),
(39, '5.00 Has', 'Norte: Terreno Benavides, Sur: Terreno Zamora, Este: Serrania, Oeste: Linea', 39, 39),
(40, '3.25 Has', 'Norte: Terreno Avila, Sur: Terreno Lira, Este: Arroyo, Oeste: Sendero', 40, 40),
(41, '7.50 Has', 'Norte: Terreno Alvarado, Sur: Terreno Ayala, Este: Terreno Zuniga, Oeste: Carretera', 41, 41),
(42, '4.80 Has', 'Norte: Terreno Morales, Sur: Terreno Barrera, Este: Rio, Oeste: Camino', 42, 42),
(43, '6.25 Has', 'Norte: Terreno Nieto, Sur: Terreno Cornejo, Este: Monte Alto, Oeste: Brecha', 43, 43),
(44, '5.50 Has', 'Norte: Terreno Miranda, Sur: Terreno Hernandez, Este: Terreno Lara, Oeste: Carretera', 44, 44),
(45, '3.75 Has', 'Norte: Terreno Salas, Sur: Terreno Nava, Este: Lindero, Oeste: Sendero', 45, 45),
(46, '8.25 Has', 'Norte: Terreno Mejia, Sur: Terreno Peralta, Este: Rio, Oeste: Camino Rural', 46, 46),
(47, '4.25 Has', 'Norte: Terreno Guzman, Sur: Terreno Rodriguez, Este: Montaña, Oeste: Linea', 47, 47),
(48, '6.00 Has', 'Norte: Terreno Mendez, Sur: Terreno Garcia, Este: Terreno Carranza, Oeste: Carretera', 48, 48),
(49, '5.75 Has', 'Norte: Terreno Cruz, Sur: Terreno Gonzalez, Este: Rio Verde, Oeste: Camino', 49, 49),
(50, '3.50 Has', 'Norte: Terreno Hernandez, Sur: Terreno Ramirez, Este: Arroyo, Oeste: Sendero', 50, 50),
(51, '7.80 Has', 'Norte: Terreno Valencia, Sur: Terreno Sanchez, Este: Terreno Torres, Oeste: Carretera', 51, 51),
(52, '4.50 Has', 'Norte: Terreno Gonzalez, Sur: Terreno Vazquez, Este: Monte, Oeste: Arroyo', 52, 52),
(53, '6.50 Has', 'Norte: Terreno Perez, Sur: Terreno Rodriguez, Este: Rio, Oeste: Camino Rural', 53, 53),
(54, '5.25 Has', 'Norte: Terreno Martinez, Sur: Terreno Sanchez, Este: Serrania, Oeste: Linea', 54, 54),
(55, '3.80 Has', 'Norte: Terreno Ramirez, Sur: Terreno Torres, Este: Lindero, Oeste: Sendero', 55, 55),
(56, '8.00 Has', 'Norte: Terreno Flores, Sur: Terreno Rivera, Este: Terreno Vazquez, Oeste: Carretera', 56, 56),
(57, '4.75 Has', 'Norte: Terreno Morales, Sur: Terreno Reyes, Este: Rio, Oeste: Camino', 57, 57),
(58, '6.25 Has', 'Norte: Terreno Gutierrez, Sur: Terreno Jimenez, Este: Monte Alto, Oeste: Brecha', 58, 58),
(59, '5.50 Has', 'Norte: Terreno Ruiz, Sur: Terreno Vega, Este: Terreno Herrera, Oeste: Carretera', 59, 59),
(60, '3.25 Has', 'Norte: Terreno Campos, Sur: Terreno Navarro, Este: Arroyo, Oeste: Sendero', 60, 60),
(61, '7.50 Has', 'Norte: Terreno Mendez, Sur: Terreno Luna, Este: Terreno Sandoval, Oeste: Carretera', 61, 61),
(62, '4.50 Has', 'Norte: Terreno Cortez, Sur: Terreno Moreno, Este: Rio, Oeste: Camino Rural', 62, 62),
(63, '6.75 Has', 'Norte: Terreno Medina, Sur: Terreno Escobedo, Este: Montaña, Oeste: Linea', 63, 63),
(64, '5.00 Has', 'Norte: Terreno Vargas, Sur: Terreno Cordoba, Este: Terreno Estrada, Oeste: Carretera', 64, 64),
(65, '3.75 Has', 'Norte: Terreno Huerta, Sur: Terreno Salazar, Este: Lindero, Oeste: Sendero', 65, 65),
(66, '8.50 Has', 'Norte: Terreno Lozano, Sur: Terreno Garcia, Este: Terreno Ramos, Oeste: Camino Rural', 66, 66),
(67, '4.25 Has', 'Norte: Terreno Hernandez, Sur: Terreno Lopez, Este: Rio, Oeste: Arroyo', 67, 67),
(68, '6.00 Has', 'Norte: Terreno Chavez, Sur: Terreno Santos, Este: Monte Alto, Oeste: Brecha', 68, 68),
(69, '5.80 Has', 'Norte: Terreno Castillo, Sur: Terreno Ochoa, Este: Terreno Valencia, Oeste: Carretera', 69, 69),
(70, '3.50 Has', 'Norte: Terreno Aguilar, Sur: Terreno Rojas, Este: Arroyo, Oeste: Sendero', 70, 70),
(71, '7.25 Has', 'Norte: Terreno Molina, Sur: Terreno Ibarra, Este: Terreno Flores, Oeste: Carretera', 71, 71),
(72, '4.80 Has', 'Norte: Terreno Delgado, Sur: Terreno Murillo, Este: Rio, Oeste: Camino', 72, 72),
(73, '6.50 Has', 'Norte: Terreno Ponce, Sur: Terreno Benites, Este: Monte, Oeste: Linea', 73, 73),
(74, '5.25 Has', 'Norte: Terreno Arias, Sur: Terreno Cifuentes, Este: Terreno Acosta, Oeste: Carretera', 74, 74),
(75, '3.80 Has', 'Norte: Terreno Solano, Sur: Terreno Galvez, Este: Lindero, Oeste: Sendero', 75, 75),
(76, '8.00 Has', 'Norte: Terreno Tapia, Sur: Terreno Pineda, Este: Terreno Vera, Oeste: Camino Rural', 76, 76),
(77, '4.50 Has', 'Norte: Terreno Arellano, Sur: Terreno Villegas, Este: Rio, Oeste: Arroyo', 77, 77),
(78, '6.75 Has', 'Norte: Terreno Plata, Sur: Terreno Angeles, Este: Monte Alto, Oeste: Brecha', 78, 78),
(79, '5.00 Has', 'Norte: Terreno Carrillo, Sur: Terreno Maciel, Este: Terreno Arreola, Oeste: Carretera', 79, 79),
(80, '3.25 Has', 'Norte: Terreno Benavides, Sur: Terreno Zamora, Este: Arroyo, Oeste: Sendero', 80, 80),
(81, '7.50 Has', 'Norte: Terreno Avila, Sur: Terreno Lira, Este: Terreno Alvarado, Oeste: Carretera', 81, 81),
(82, '4.75 Has', 'Norte: Terreno Ayala, Sur: Terreno Zuniga, Este: Rio, Oeste: Camino', 82, 82),
(83, '6.25 Has', 'Norte: Terreno Morales, Sur: Terreno Barrera, Este: Montaña, Oeste: Linea', 83, 83),
(84, '5.50 Has', 'Norte: Terreno Nieto, Sur: Terreno Cornejo, Este: Terreno Miranda, Oeste: Carretera', 84, 84),
(85, '3.75 Has', 'Norte: Terreno Hernandez, Sur: Terreno Lara, Este: Lindero, Oeste: Sendero', 85, 85),
(86, '8.25 Has', 'Norte: Terreno Salas, Sur: Terreno Nava, Este: Terreno Mejia, Oeste: Camino Rural', 86, 86),
(87, '4.25 Has', 'Norte: Terreno Peralta, Sur: Terreno Guzman, Este: Rio, Oeste: Arroyo', 87, 87),
(88, '6.00 Has', 'Norte: Terreno Rodriguez, Sur: Terreno Mendez, Este: Monte, Oeste: Brecha', 88, 88),
(89, '5.75 Has', 'Norte: Terreno Garcia, Sur: Terreno Carranza, Este: Terreno Cruz, Oeste: Carretera', 89, 89),
(90, '3.50 Has', 'Norte: Terreno Gonzalez, Sur: Terreno Hernandez, Este: Arroyo, Oeste: Sendero', 90, 90),
(91, '7.80 Has', 'Norte: Terreno Martinez, Sur: Terreno Sanchez, Este: Terreno Ramirez, Oeste: Carretera', 91, 91),
(92, '4.50 Has', 'Norte: Terreno Torres, Sur: Terreno Flores, Este: Rio, Oeste: Camino', 92, 92),
(93, '6.50 Has', 'Norte: Terreno Rivera, Sur: Terreno Morales, Este: Monte Alto, Oeste: Linea', 93, 93),
(94, '5.25 Has', 'Norte: Terreno Reyes, Sur: Terreno Gutierrez, Este: Terreno Jimenez, Oeste: Carretera', 94, 94),
(95, '3.80 Has', 'Norte: Terreno Ruiz, Sur: Terreno Vega, Este: Lindero, Oeste: Sendero', 95, 95),
(96, '8.00 Has', 'Norte: Terreno Herrera, Sur: Terreno Campos, Este: Terreno Navarro, Oeste: Camino Rural', 96, 96),
(97, '4.75 Has', 'Norte: Terreno Mendez, Sur: Terreno Luna, Este: Rio, Oeste: Arroyo', 97, 97),
(98, '6.25 Has', 'Norte: Terreno Sandoval, Sur: Terreno Cortez, Este: Monte, Oeste: Brecha', 98, 98),
(99, '5.50 Has', 'Norte: Terreno Moreno, Sur: Terreno Medina, Este: Terreno Escobedo, Oeste: Carretera', 99, 99),
(100, '3.75 Has', 'Norte: Terreno Vargas, Sur: Terreno Cordoba, Este: Arroyo, Oeste: Sendero', 100, 100);
SET FOREIGN_KEY_CHECKS = 1;