SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE personas;
INSERT INTO personas (id_persona, nombre, ap_p, ap_m) VALUES
(1, 'Jose Luis', 'Hernandez', 'Garcia'),
(2, 'Maria Elena', 'Rodriguez', 'Lopez'),
(3, 'Pedro Antonio', 'Martinez', 'Sanchez'),
(4, 'Juan Carlos', 'Gonzalez', 'Fernandez'),
(5, 'Rosa Maria', 'Perez', 'Gomez'),
(6, 'Miguel Angel', 'Ramirez', 'Torres'),
(7, 'Ana Laura', 'Flores', 'Rivera'),
(8, 'Carlos Eduardo', 'Morales', 'Vazquez'),
(9, 'Laura Patricia', 'Reyes', 'Cruz'),
(10, 'Francisco Javier', 'Gutierrez', 'Ortiz'),
(11, 'Patricia Guadalupe', 'Jimenez', 'Mendoza'),
(12, 'Roberto Carlos', 'Ruiz', 'Alvarez'),
(13, 'Sandra Ivette', 'Vega', 'Diaz'),
(14, 'Alejandro', 'Herrera', 'Romero'),
(15, 'Veronica', 'Campos', 'Nava'),
(16, 'David Omar', 'Navarro', 'Leiva'),
(17, 'Elena', 'Mendez', 'Castro'),
(18, 'Jorge Alberto', 'Luna', 'Orozco'),
(19, 'Gabriela', 'Sandoval', 'Aguilar'),
(20, 'Luis Manuel', 'Cortez', 'Arias'),
(21, 'Cristina', 'Moreno', 'Castillo'),
(22, 'Raul', 'Medina', 'Valdez'),
(23, 'Maria Guadalupe', 'Escobedo', 'Aguirre'),
(24, 'Sergio', 'Vargas', 'Campos'),
(25, 'Ana Bertha', 'Cordoba', 'Zamora'),
(26, 'Javier', 'Estrada', 'Linares'),
(27, 'Leticia', 'Mejia', 'Santos'),
(28, 'Ignacio', 'Huerta', 'Trujillo'),
(29, 'Carmen', 'Salazar', 'Ramos'),
(30, 'Manuel', 'Lozano', 'Barrera'),
(31, 'Diana', 'Garcia', 'Marin'),
(32, 'Victor Hugo', 'Ramos', 'Cerda'),
(33, 'Alma Rosa', 'Hernandez', 'Espinoza'),
(34, 'Daniel', 'Lopez', 'Mendez'),
(35, 'Ofelia', 'Chavez', 'Guerrero'),
(36, 'Marco Antonio', 'Santos', 'Perez'),
(37, 'Blanca', 'Castillo', 'Toledo'),
(38, 'Francisco', 'Ochoa', 'Valencia'),
(39, 'Angeles', 'Valencia', 'Montoya'),
(40, 'Gustavo', 'Aguilar', 'Soto'),
(41, 'Esmeralda', 'Rojas', 'Mora'),
(42, 'Adrian', 'Molina', 'Velasco'),
(43, 'Marisol', 'Ibarra', 'Rentería'),
(44, 'Oscar', 'Flores', 'Quintana'),
(45, 'Yolanda', 'Delgado', 'Uribe'),
(46, 'Enrique', 'Murillo', 'Zarate'),
(47, 'Maria Trinidad', 'Ponce', 'Vigil'),
(48, 'Ricardo', 'Benitez', 'Palacios'),
(49, 'Luz Maria', 'Arias', 'Granados'),
(50, 'Fernando', 'Cifuentes', 'Arriaga'),
(51, 'Claudia', 'Acosta', 'Lira'),
(52, 'Jose Manuel', 'Solano', 'Cardenas'),
(53, 'Silvia', 'Galvez', 'Cornejo'),
(54, 'Arturo', 'Tapia', 'Saldivar'),
(55, 'Irene', 'Pineda', 'Cano'),
(56, 'Armando', 'Vera', 'Galicia'),
(57, 'Teresa', 'Arellano', 'Otero'),
(58, 'Saul', 'Villegas', 'Palma'),
(59, 'Maria Clementina', 'Plata', 'Becerra'),
(60, 'Israel', 'Angeles', 'Gonzaga'),
(61, 'Juana', 'Carrillo', 'Levy'),
(62, 'Juan Pablo', 'Maciel', 'Cabrera'),
(63, 'Elizabeth', 'Arreola', 'Escobar'),
(64, 'Felipe de Jesus', 'Benavides', 'Anaya'),
(65, 'Gloria', 'Zamora', 'Guevara'),
(66, 'Hector', 'Avila', 'Hernandez'),
(67, 'Martha', 'Lira', 'Segovia'),
(68, 'Ruben', 'Alvarado', 'Pimentel'),
(69, 'Norma', 'Ayala', 'Bernal'),
(70, 'Alfredo', 'Zuniga', 'Gamez'),
(71, 'Alicia', 'Morales', 'Vera'),
(72, 'Ernesto', 'Barrera', 'Leal'),
(73, 'Maria de Jesus', 'Nieto', 'Rosas'),
(74, 'Jose de Jesus', 'Cornejo', 'Ortega'),
(75, 'Sofia', 'Miranda', 'Valle'),
(76, 'Tomas', 'Hernandez', 'Acevedo'),
(77, 'Lourdes', 'Lara', 'Becerra'),
(78, 'Damian', 'Salas', 'Zepeda'),
(79, 'Karina', 'Nava', 'Peralta'),
(80, 'Eduardo', 'Mejia', 'Gonzalez'),
(81, 'Miriam', 'Peralta', 'Avila'),
(82, 'Julio', 'Guzman', 'Lopez'),
(83, 'Azucena', 'Rodriguez', 'Herrera'),
(84, 'Salvador', 'Mendez', 'Rodriguez'),
(85, 'Rosa Isela', 'Garcia', 'Soto'),
(86, 'Genaro', 'Carranza', 'Morales'),
(87, 'Maria de la Luz', 'Cruz', 'Aguilar'),
(88, 'Cesar', 'Gonzalez', 'Martinez'),
(89, 'Patricia', 'Hernandez', 'Ramirez'),
(90, 'Martin', 'Valencia', 'Perez'),
(91, 'Beatriz', 'Gonzalez', 'Garcia'),
(92, 'Ramon', 'Torres', 'Flores'),
(93, 'Elvia', 'Sanchez', 'Mendez'),
(94, 'Humberto', 'Vazquez', 'Ruiz'),
(95, 'Ma. Elena', 'Perez', 'Garcia'),
(96, 'Luis', 'Rodriguez', 'Lopez'),
(97, 'Maria Antonieta', 'Martinez', 'Gonzalez'),
(98, 'Jesus', 'Sanchez', 'Torres'),
(99, 'Carolina', 'Ramirez', 'Perez'),
(100, 'Juan Manuel', 'Garcia', 'Rodriguez');
SET FOREIGN_KEY_CHECKS = 1;