SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE servicios;
INSERT INTO servicios (id_servicio, asesor, documentacion, medicion, solicitudes, id_usuario) VALUES
(1, 'Roberto Garcia Lopez', 'Completa', 'Realizada', 'Certificado de Parcela', 1),
(2, 'Patricia Hernandez Martinez', 'Completa', 'Pendiente', 'Constancia de posesion', 2),
(3, 'Luis Alberto Sanchez Rodriguez', 'Completa', 'Realizada', 'Cesion de derechos', 3),
(4, 'Ana Maria Torres Ramirez', 'Completa', 'Realizada', 'Actualizacion de datos', 4),
(5, 'Miguel Flores Gonzalez', 'Incompleta', 'Pendiente', 'Certificado de parcela', 5),
(6, 'Claudia Vazquez Perez', 'Completa', 'Realizada', 'Constancia de ejidatario', 6),
(7, 'Carlos Mendez Jimenez', 'Completa', 'Realizada', 'Deslinde de parcela', 7),
(8, 'Laura Ruiz Hernandez', 'Completa', 'Pendiente', 'Certificado parcelario', 8),
(9, 'Jorge Alvarez Castro', 'Completa', 'Realizada', 'Cesion de derechos', 9),
(10, 'Sandra Nunez Morales', 'Completa', 'Realizada', 'Constancia de propiedad', 10),
(11, 'Fernando Gutierrez Ortiz', 'Completa', 'Pendiente', 'Cambio de titular', 11),
(12, 'Diana Vega Diaz', 'Completa', 'Realizada', 'Certificado de parcela', 12),
(13, 'Alejandro Reyes Flores', 'Completa', 'Realizada', 'Constancia de posesion', 13),
(14, 'Maria del Carmen Luna Vera', 'Incompleta', 'Pendiente', 'Cesion de derechos', 14),
(15, 'Raul Campos Morales', 'Completa', 'Realizada', 'Deslinde administrativo', 15),
(16, 'Guadalupe Navarro Sandoval', 'Completa', 'Realizada', 'Certificado ejidal', 16),
(17, 'Jose Manuel Cortez Aguilar', 'Completa', 'Pendiente', 'Constancia de vigencia', 17),
(18, 'Veronica Medina Estrada', 'Completa', 'Realizada', 'Actualizacion de parcela', 18),
(19, 'Juan Carlos Lozano Herrera', 'Completa', 'Realizada', 'Certificado de parcela', 19),
(20, 'Carmen Arias Ramos', 'Completa', 'Pendiente', 'Constancia de posesion', 20),
(21, 'Sergio Chavez Garcia', 'Completa', 'Realizada', 'Cesion de derechos', 21),
(22, 'Martha Romero Torres', 'Completa', 'Realizada', 'Deslinde de parcela', 22),
(23, 'Francisco Guzman Espinoza', 'Completa', 'Realizada', 'Certificado parcelario', 23),
(24, 'Leticia Aguilar Mendez', 'Completa', 'Pendiente', 'Constancia de ejidatario', 24),
(25, 'Arturo Pineda Nava', 'Completa', 'Realizada', 'Cambio de nombre', 25),
(26, 'Irma Rojas Molina', 'Completa', 'Realizada', 'Certificado de parcela', 26),
(27, 'David Cruz Lopez', 'Incompleta', 'Pendiente', 'Deslinde tecnico', 27),
(28, 'Rosa Maria Soto Reyes', 'Completa', 'Realizada', 'Constancia de posesion', 28),
(29, 'Hector Vigil Mendoza', 'Completa', 'Realizada', 'Cesion de derechos', 29),
(30, 'Silvia Valencia Jimenez', 'Completa', 'Pendiente', 'Actualizacion de datos', 30),
(31, 'Oscar Barrera Gonzalez', 'Completa', 'Realizada', 'Certificado de parcela', 31),
(32, 'Olga Leon Sanchez', 'Completa', 'Realizada', 'Constancia de propiedad', 32),
(33, 'Armando Cabrera Torres', 'Completa', 'Realizada', 'Cesion de derechos', 33),
(34, 'Teresa Salas Morales', 'Completa', 'Pendiente', 'Deslinde de parcela', 34),
(35, 'Javier Zamora Hernandez', 'Completa', 'Realizada', 'Certificado ejidal', 35),
(36, 'Maria Elena Palacios Garcia', 'Completa', 'Realizada', 'Constancia de posesion', 36),
(37, 'Enrique Carrillo Rodriguez', 'Completa', 'Pendiente', 'Deslinde de parcela', 37),
(38, 'Lucia Benitez Flores', 'Completa', 'Realizada', 'Certificado de parcela', 38),
(39, 'Ramon Perez Martinez', 'Completa', 'Realizada', 'Constancia de vigencia', 39),
(40, 'Ana Lilia Hernandez Vazquez', 'Completa', 'Realizada', 'Cesion de derechos', 40),
(41, 'Daniel Mendez Cruz', 'Completa', 'Pendiente', 'Actualizacion de parcela', 41),
(42, 'Gloria Garcia Luna', 'Completa', 'Realizada', 'Certificado de parcela', 42),
(43, 'Saul Rodriguez Ramirez', 'Completa', 'Realizada', 'Constancia de posesion', 43),
(44, 'Maria de la Luz Reyes Torres', 'Completa', 'Realizada', 'Cesion de derechos', 44),
(45, 'Manuel Vargas Jimenez', 'Incompleta', 'Pendiente', 'Deslinde administrativo', 45),
(46, 'Patricia Silva Santos', 'Completa', 'Realizada', 'Certificado parcelario', 46),
(47, 'Alberto Gonzalez Morales', 'Completa', 'Realizada', 'Constancia de ejidatario', 47),
(48, 'Elvia Castillo Navarro', 'Completa', 'Pendiente', 'Cambio de titular', 48),
(49, 'Ricardo Delgado Cortez', 'Completa', 'Realizada', 'Certificado de parcela', 49),
(50, 'Sofia Aguirre Campos', 'Completa', 'Realizada', 'Constancia de posesion', 50),
(51, 'Jose de Jesus Moreno Garcia', 'Completa', 'Pendiente', 'Cesion de derechos', 51),
(52, 'Maria Trinidad Estrada Herrera', 'Completa', 'Realizada', 'Deslinde de parcela', 52),
(53, 'Gustavo Cervantes Martinez', 'Completa', 'Realizada', 'Certificado ejidal', 53),
(54, 'Ana Patricia Rivera Lopez', 'Completa', 'Realizada', 'Constancia de propiedad', 54),
(55, 'Juan Pablo Espinoza Rodriguez', 'Completa', 'Pendiente', 'Cambio de nombre', 55),
(56, 'Laura Elena Garcia Gutierrez', 'Completa', 'Realizada', 'Certificado de parcela', 56),
(57, 'Luis Fernando Hernandez Mendez', 'Completa', 'Realizada', 'Constancia de posesion', 57),
(58, 'Maria Isabel Gomez Perez', 'Completa', 'Realizada', 'Deslinde de parcela', 58),
(59, 'Victor Manuel Sanchez Torres', 'Completa', 'Pendiente', 'Certificado parcelario', 59),
(60, 'Claudia Ivette Ramirez Sanchez', 'Completa', 'Realizada', 'Constancia de ejidatario', 60),
(61, 'Eduardo Lopez Garcia', 'Completa', 'Realizada', 'Cesion de derechos', 61),
(62, 'Rosario Flores Gonzalez', 'Completa', 'Realizada', 'Actualizacion de datos', 62),
(63, 'Felipe Martinez Rodriguez', 'Completa', 'Pendiente', 'Certificado de parcela', 63),
(64, 'Yolanda Perez Hernandez', 'Completa', 'Realizada', 'Constancia de posesion', 64),
(65, 'Antonio Soto Ramirez', 'Incompleta', 'Pendiente', 'Cesion de derechos', 65),
(66, 'Maria del Rosario Cruz Vazquez', 'Completa', 'Realizada', 'Deslinde de parcela', 66),
(67, 'Alfredo Jimenez Morales', 'Completa', 'Realizada', 'Certificado ejidal', 67),
(68, 'Beatriz Ortega Garcia', 'Completa', 'Realizada', 'Constancia de propiedad', 68),
(69, 'Mario Hernandez Torres', 'Completa', 'Pendiente', 'Cambio de titular', 69),
(70, 'Ana Guadalupe Mendoza Lopez', 'Completa', 'Realizada', 'Certificado de parcela', 70),
(71, 'Gerardo Vazquez Ruiz', 'Completa', 'Realizada', 'Constancia de posesion', 71),
(72, 'Lidia Garcia Rodriguez', 'Completa', 'Realizada', 'Cesion de derechos', 72),
(73, 'Jorge Luis Ramirez Flores', 'Completa', 'Pending', 'Deslinde de parcela', 73),
(74, 'Maria de Jesus Morales Sanchez', 'Completa', 'Realizada', 'Certificado parcelario', 74),
(75, 'Mauricio Torres Hernandez', 'Completa', 'Realizada', 'Constancia de ejidatario', 75),
(76, 'Sandra Luz Cortez Garcia', 'Completa', 'Pendiente', 'Actualizacion de parcela', 76),
(77, 'Juan Manuel Vega Martinez', 'Completa', 'Realizada', 'Certificado de parcela', 77),
(78, 'Maria de la Paz Luna Jimenez', 'Completa', 'Realizada', 'Constancia de posesion', 78),
(79, 'Francisco Javier Aguilar Perez', 'Completa', 'Realizada', 'Cesion de derechos', 79),
(80, 'Karina Herrera Torres', 'Completa', 'Pendiente', 'Deslinde de parcela', 80),
(81, 'Ignacio Navarro Garcia', 'Completa', 'Realizada', 'Certificado ejidal', 81),
(82, 'Maria de los Angeles Medina Rodriguez', 'Completa', 'Realizada', 'Constancia de propiedad', 82),
(83, 'Ivan Sandoval Martinez', 'Completa', 'Realizada', 'Cambio de nombre', 83),
(84, 'Veronica Castillo Sanchez', 'Completa', 'Pendiente', 'Certificado de parcela', 84),
(85, 'Israel Perez Hernandez', 'Completa', 'Realizada', 'Constancia de posesion', 85),
(86, 'Maria del Consuelo Lopez Gutierrez', 'Completa', 'Realizada', 'Deslinde de parcela', 86),
(87, 'Luis Miguel Gonzalez Ramirez', 'Completa', 'Realizada', 'Certificado parcelario', 87),
(88, 'Ana Karen Reyes Cruz', 'Completa', 'Realizada', 'Constancia de ejidatario', 88),
(89, 'Marco Antonio Vazquez Torres', 'Completa', 'Pendiente', 'Cambio de titular', 89),
(90, 'Gabriela Mendez Jimenez', 'Completa', 'Realizada', 'Certificado de parcela', 90),
(91, 'Pedro Gutierrez Martinez', 'Completa', 'Realizada', 'Constancia de posesion', 91),
(92, 'Maria Guadalupe Sanchez Lopez', 'Completa', 'Realizada', 'Cesion de derechos', 92),
(93, 'Carlos Rodriguez Garcia', 'Completa', 'Realizada', 'Deslinde de parcela', 93),
(94, 'Maria del Pilar Alvarez Hernandez', 'Completa', 'Pendiente', 'Certificado ejidal', 94),
(95, 'Jesus Morales Torres', 'Completa', 'Realizada', 'Constancia de propiedad', 95),
(96, 'Liliana Flores Rodriguez', 'Completa', 'Realizada', 'Cambio de nombre', 96),
(97, 'Roberto Carlos Escobedo Mendez', 'Completa', 'Realizada', 'Certificado de parcela', 97),
(98, 'Maria del Carmen Campos Ramirez', 'Completa', 'Realizada', 'Constancia de posesion', 98),
(99, 'Alejandro Valencia Sanchez', 'Completa', 'Pendiente', 'Cesion de derechos', 99),
(100, 'Cynthia Gonzalez Perez', 'Completa', 'Realizada', 'Deslinde de parcela', 100);
SET FOREIGN_KEY_CHECKS = 1;