import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { SistemaResolver } from './sistema-ejidatario.resolver';
import {
  Cesion,
  Derecho,
  Certificado,
  Deslinde,
  Detalle,
  Ejido,
  Ejidatario,
  Constancia,
  Empleado,
  Estado,
  Expediente,
  Municipio,
  Pago,
  Parcela,
  Persona,
  Servicio,
  Usuario,
} from './entities';
import {
  CertificadoService,
  CesionService,
  ConstanciaService,
  DerechosService,
  DeslindeService,
  DetalleService,
  EjidatarioService,
  EjidoService,
  EmpleadoService,
  EstadosService,
  ExpedienteService,
  MunicipioService,
  PagoService,
  ParcelaService,
  PersonaService,
  ServicioService,
  UsuarioService,
  DashboardService,
} from './services';
import {
  CertificadoResolver,
  CesionResolver,
  ConstanciaResolver,
  DerechoResolver,
  DeslindeResolver,
  DetallesResolver,
  DashboardResolver,
  EjidatarioResolver,
  EjidoResolver,
  EmpleadosResolver,
  EstadosResolver,
  ExpedienteResolver,
  MunicipioResolver,
  PagoResolver,
  ParcelaResolver,
  PersonaResolver,
  ServicioResolver,
  UsuarioResolver,
} from './resolvers';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      Cesion,
      Derecho,
      Certificado,
      Deslinde,
      Detalle,
      Ejido,
      Ejidatario,
      Constancia,
      Empleado,
      Estado,
      Expediente,
      Municipio,
      Pago,
      Parcela,
      Persona,
      Servicio,
      Usuario,
    ]),
  ],
  providers: [
    CertificadoService,
    CesionService,
    ConstanciaService,
    DerechosService,
    DeslindeService,
    DetalleService,
    DashboardService,
    EjidatarioService,
    EjidoService,
    EmpleadoService,
    EstadosService,
    ExpedienteService,
    MunicipioService,
    PagoService,
    ParcelaService,
    PersonaService,
    ServicioService,
    UsuarioService,
    CertificadoResolver,
    CesionResolver,
    ConstanciaResolver,
    DerechoResolver,
    DeslindeResolver,
    DetallesResolver,
    DashboardResolver,
    EjidatarioResolver,
    EjidoResolver,
    EmpleadosResolver,
    EstadosResolver,
    ExpedienteResolver,
    MunicipioResolver,
    PagoResolver,
    ParcelaResolver,
    PersonaResolver,
    ServicioResolver,
    UsuarioResolver,
  ],
  exports: [UsuarioService],
})
export class SistemaEjidatarioModule {}
